server:
  port: 7001

spring:
  application:
    name: Disaster-Manage-And-Control

  datasource:
    url: jdbc:mysql://localhost:3306/dismancendb?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jlmnb
    password: 123456

